### ISSUE TITLE
Topoisomerase question

### ISSUE THREAD

**Issue by mavino** [Farre-lab/Spermatid_DSB_paper#1]
Hi, I am trying to use your code to run get the Z score in the same way you did for your paper. However, at a certain point in the paper you say that you have have got a z-score "between the topoisomerase II consensus motif (RNYNNCNNGYNGKTNYNY) and spermatid post-meiotic DSB locations". Now, I was wondering how did you do that if regionR acceptes two bed files. Do you possible have a bed file with the genomic locations of the topoisomerase II?
Thank you very much

**Comment by marta-fb** [comment]
Hi Mariano,

We scanned the genome for the topoisomerase II motif using FIMO [https://meme-suite.org/meme/doc/fimo.html](url). And used this as input for regioneR with our DSB locations. 

Cheers
Marta
